### ISSUE TITLE
mysqldump issue

### ISSUE THREAD

**Issue by rasdotsu** [opennet/FSBackup#4]
mysql dump gives:

mysqldump: ambiguous option '--all' (all-databases, allow-keywords)
mysqldump: ambiguous option '--all' (all-databases, allow-keywords)
mysqldump: ambiguous option '--all' (all-databases, allow-keywords)
mysqldump: ambiguous option '--all' (all-databases, allow-keywords)

latest fsbackup from github, backup method:

backup_method="db"

easy fix - need just remove --all

**Comment by rasdotsu** [comment]
easy fix - need just remove --all

**Comment by opennet** [comment]
fixed
